### ISSUE TITLE
Fix `deneb` `include_attestation_from_previous_fork_with_new_range` test

### ISSUE THREAD

**Issue by ethDreamer** [ethereum/consensus-spec-tests#35]
In the latest release ([v1.4.0-beta.0](https://github.com/ethereum/consensus-spec-tests/releases/tag/v1.4.0-beta.0)), there's a new test called [`include_attestation_from_previous_fork_with_new_range`](https://github.com/ethereum/consensus-specs/blob/dev/tests/core/pyspec/eth2spec/test/deneb/sanity/test_blocks.py#L120) meant to ensure the new attestation inclusion rules under [EIP-7045](https://eips.ethereum.org/EIPS/eip-7045) apply to attestations from the final `CAPELLA` epoch. This is the only generated test which [makes use of](https://github.com/ethereum/consensus-specs/blob/dev/tests/core/pyspec/eth2spec/test/deneb/sanity/test_blocks.py#L117C1-L119C3) the [`@spec_configured_state_test`](https://github.com/ethereum/consensus-specs/blob/dev/tests/core/pyspec/eth2spec/test/context.py#L290) override.

This override [emits a `config.yaml`](https://github.com/ethereum/consensus-specs/blob/dev/tests/core/pyspec/eth2spec/test/context.py#L625) file in the generated test directory. There are several problems with this:

1) The [sanity test definition](https://github.com/ethereum/consensus-specs/blob/dev/tests/formats/sanity/blocks.md) does not say to expect a `config.yaml`
2) The generated `config.yaml` is invalid:
```yaml
# this is the mainnet example
ALTAIR_FORK_EPOCH: 74240
...
BELLATRIX_FORK_EPOCH: 144896
...
CAPELLA_FORK_EPOCH: 194048
...
DENEB_FORK_EPOCH: 2
```
3) The generated `config.yaml` is missing the following fields which (without modification) prevent lighthouse from ingesting it:
 - `DEPOSIT_CHAIN_ID`
 - `DEPOSIT_NETWORK_ID`
 - `DEPOSIT_CONTRACT_ADDRESS`
4) If clients silently ignore the `config.yaml` (which is likely), they will use the default testing config:
```yaml
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_EPOCH: 0
```
This test generates the attestation in epoch `1`, which is meant to be a `CAPELLA` attestation. But with the default config, it ends up being within `DENEB`. This would mean we are only testing that the new rules apply to attestations within `DENEB` instead of ensuring they also apply to attestations from the final `CAPELLA` epoch.
